server:
  servlet:
    session:
      cookie:
        max-age: 600
  port: 9191
  tomcat:
    max-connections: 200
    max-threads: 200
    ssl:
      key-store: githubaccess.p12
      key-store-password: password
      keyStoreType: PKCS12
      keyAlias: github-access-service
    enabled: false
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    protocol: TLS
    enabled-protocols: TLSv1.2

spring:
  application:
    name: github-access-service
  datasource:
    url: jdbc:mysql://192.168.1.5:3306/GITHUB_ACCESS?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

app:
  github:
    access-token: ACCESS_TOKE

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36}::%M:%L - %msg%n"
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info
    root: info
    org.springframework.web: info
    org.hibernate: info
    com.coliand.test.githubaccess: debug
  file:
    name: github-access-service.log
