CREATE DATABASE GITHUB_ACCESS;

USE GITHUB_ACCESS;

CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
GRANT SELECT,DELETE,INSERT,UPDATE ON GITHUB_ACCESS.* TO 'admin'@'%';	

CREATE TABLE AUDIT_REQUESTS_PROCESS (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(255) NOT NULL,
	DATE DATETIME NOT NULL,
	HTTP_METHOD VARCHAR(255) NOT NULL,
	REQUEST_PARAMS VARCHAR(550),
	RESPONSE_CODE VARCHAR(255) NOT NULL
);